name: MATLAB Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['MATLAB']

    steps:
    - uses: actions/checkout@v2
    - name: Customize git
      run: |
        git submodule update --init --recursive
        git fetch --prune --unshallow
    - name: Clone the matlab-tests repository
      run: |
        git clone https://github.com/dqrobotics/matlab-tests
    - name: Clone the matlab-examples repository
      run: |
        git clone https://github.com/dqrobotics/matlab-examples
    - name: Set correct execution path
      run: |
        printf "folder=fileparts(which('startup.m'))\n
        addpath(genpath(folder))" > startup.m
    - name: Run matlab-tests
      run: |
        matlab -nodisplay -nosplash -nodesktop -r "run('run_basic_tests')"
    - name: Run matlab-examples
      run: |
        matlab -nodisplay -nosplash -nodesktop -r "run('run_examples_test')"
